spring.application.name=grpc-sample

# Port aplikasi REST (Spring MVC)
server.port=8080

# Port gRPC server (net.devh grpc-server-spring-boot-starter)
grpc.server.port=9090

# Alamat gRPC client "greeting-service" mengarah ke gRPC server di atas
grpc.client.greeting-service.address=static://localhost:9090
grpc.client.greeting-service.negotiation-type=plaintext
